export const issueStrings = {
  en: {
    gpsUnavailable: "Unable to get your location. Turn on location services and try again at the issue site.",
    title: "Field issues", create: "Create issue", priority: "Priority Work", review: "Issue review", monitor: "AO complaints",
    subtitle: "Spot it. Report it. Track it to resolution.", prioritySub: "Visit assigned locations and submit your report.", reviewSub: "Review supervisor evidence and close verified issues.",
    all: "All issues", PENDING: "Pending", REPORT_SUBMITTED: "Supervisor submitted report", REJECTED: "Correction required", CLOSED: "Resolved / Closed",
    LITTER_BIN: "Litter bin", TOILET: "Toilet", BEAT: "Beat", OTHER: "Other", otherName: "Issue category name", description: "Describe the issue and nearby landmark", category: "Choose a category", photo: "Take a photo", retake: "Retake photo", next: "Continue to location", back: "Back", cancel: "Cancel", submit: "Submit issue", step1: "01 · Photo & details", step2: "02 · Zone & ward", zone: "Select zone", ward: "Select ward", location: "Issue location", locate: "Capture current location", locationHint: "Capture the location while you are at the issue site.", ready: "Location captured", pendingHint: "Your issue will appear as Pending and reach the assigned supervisor.",
    report: "Submit visit report", notes: "Describe the work completed (at least 10 characters)", visitHint: "Take a fresh photo at the site. Submit within 200 metres of the issue location.", navigate: "Directions to location", evidence: "Issue photo", history: "Report & review history", noReports: "Awaiting supervisor visit", approve: "Approve & close", reject: "Return for correction", reason: "Review note (required for rejection)", ao: "Action Officer", supervisor: "Supervisor", qc: "QC reviewer", empty: "No issues here yet", emptySub: "Issues matching this status will appear here.", retry: "Try again", loading: "Loading issues…", save: "Submitting…", success: "Issue submitted", reportSuccess: "Report submitted for QC review", reviewSuccess: "Review saved", error: "Unable to complete this action", genericError: "Please check your connection and try again.", required: "Add a photo, category, description and location before continuing.", selectLocation: "Select a zone and ward.", cameraPermission: "Allow camera access to capture an issue photo.", gpsPermission: "Allow location access to record the visit location.", previous: "Previous", nextPage: "Next", refresh: "Refresh", total: "Total complaints", officers: "Complaints by Action Officer", places: "Location", details: "View details", close: "Close", search: "Search by AO, ward or issue", noSupervisor: "No supervisor is assigned to this zone and ward. Contact your city administrator.", conflict: "This issue has changed. Refresh it before continuing.", tooFar: "Visit the issue location and submit within 200 metres.", forbidden: "You do not have access to this action.", validation: "Check the required fields and try again.", reportRequired: "Add a fresh photo and a report of at least 10 characters.", reasonRequired: "Enter a rejection reason of at least 5 characters.", reviewConfirm: "Approve this report and close the issue?", rejectConfirm: "Return this report to the supervisor for correction?", confirm: "Confirm", submitted: "Submitted", reviewed: "Reviewed", reportPhoto: "Supervisor evidence", approved: "Approved", rejected: "Rejected", open: "Open issues",
  },
  hi: {
    gpsUnavailable: "आपका स्थान नहीं मिल सका। लोकेशन चालू करें और समस्या वाले स्थान पर दोबारा प्रयास करें।",
    title: "स्थल की समस्याएँ", create: "समस्या दर्ज करें", priority: "प्राथमिकता वाले कार्य", review: "समस्याओं की समीक्षा", monitor: "कार्रवाई अधिकारी की शिकायतें",
    subtitle: "समस्या देखें, दर्ज करें और समाधान की स्थिति जानें।", prioritySub: "निर्धारित स्थान पर जाएँ और अपनी रिपोर्ट जमा करें।", reviewSub: "पर्यवेक्षक की रिपोर्ट जाँचें और समाधान की पुष्टि करें।",
    all: "सभी समस्याएँ", PENDING: "लंबित", REPORT_SUBMITTED: "पर्यवेक्षक ने रिपोर्ट जमा कर दी है", REJECTED: "सुधार आवश्यक", CLOSED: "समाधान हुआ / बंद",
    LITTER_BIN: "कूड़ादान", TOILET: "शौचालय", BEAT: "बीट", OTHER: "अन्य", otherName: "समस्या की श्रेणी का नाम", description: "समस्या और पास के पहचान चिह्न का विवरण दें", category: "श्रेणी चुनें", photo: "फोटो लें", retake: "दोबारा फोटो लें", next: "स्थान चुनने के लिए आगे बढ़ें", back: "वापस", cancel: "रद्द करें", submit: "समस्या जमा करें", step1: "01 · फोटो और विवरण", step2: "02 · ज़ोन और वार्ड", zone: "ज़ोन चुनें", ward: "वार्ड चुनें", location: "समस्या का स्थान", locate: "वर्तमान स्थान दर्ज करें", locationHint: "समस्या वाले स्थान पर मौजूद रहते हुए स्थान दर्ज करें।", ready: "स्थान दर्ज हो गया", pendingHint: "समस्या लंबित स्थिति में दिखेगी और संबंधित पर्यवेक्षक को भेजी जाएगी।",
    report: "स्थल निरीक्षण रिपोर्ट जमा करें", notes: "किए गए कार्य का विवरण दें (कम से कम 10 अक्षर)", visitHint: "स्थल पर नई फोटो लें। समस्या के स्थान से 200 मीटर के भीतर रिपोर्ट जमा करें।", navigate: "स्थान तक पहुँचने का रास्ता", evidence: "समस्या की फोटो", history: "रिपोर्ट और समीक्षा का इतिहास", noReports: "पर्यवेक्षक के निरीक्षण की प्रतीक्षा है", approve: "स्वीकृत करके बंद करें", reject: "सुधार के लिए लौटाएँ", reason: "समीक्षा टिप्पणी (अस्वीकृति के लिए आवश्यक)", ao: "कार्रवाई अधिकारी", supervisor: "पर्यवेक्षक", qc: "गुणवत्ता जाँच अधिकारी", empty: "अभी कोई समस्या नहीं है", emptySub: "इस स्थिति वाली समस्याएँ यहाँ दिखेंगी।", retry: "दोबारा प्रयास करें", loading: "समस्याएँ लोड हो रही हैं…", save: "जमा किया जा रहा है…", success: "समस्या जमा हो गई", reportSuccess: "रिपोर्ट गुणवत्ता जाँच के लिए जमा हो गई", reviewSuccess: "समीक्षा सहेज ली गई", error: "यह कार्य पूरा नहीं हो सका", genericError: "इंटरनेट कनेक्शन जाँचें और दोबारा प्रयास करें।", required: "आगे बढ़ने से पहले फोटो, श्रेणी, विवरण और स्थान दर्ज करें।", selectLocation: "ज़ोन और वार्ड चुनें।", cameraPermission: "समस्या की फोटो लेने के लिए कैमरे की अनुमति दें।", gpsPermission: "निरीक्षण का स्थान दर्ज करने के लिए लोकेशन की अनुमति दें।", previous: "पिछला", nextPage: "अगला", refresh: "ताज़ा करें", total: "कुल शिकायतें", officers: "कार्रवाई अधिकारी के अनुसार शिकायतें", places: "स्थान", details: "विवरण देखें", close: "बंद करें", search: "अधिकारी, वार्ड या समस्या खोजें", noSupervisor: "इस ज़ोन और वार्ड में कोई पर्यवेक्षक नियुक्त नहीं है। नगर प्रशासक से संपर्क करें।", conflict: "इस समस्या की स्थिति बदल गई है। आगे बढ़ने से पहले ताज़ा करें।", tooFar: "समस्या वाले स्थान पर जाएँ और 200 मीटर के भीतर रिपोर्ट जमा करें।", forbidden: "आपको इस कार्य की अनुमति नहीं है।", validation: "आवश्यक जानकारी जाँचें और दोबारा प्रयास करें।", reportRequired: "नई फोटो और कम से कम 10 अक्षरों की रिपोर्ट जोड़ें।", reasonRequired: "अस्वीकृति का कारण कम से कम 5 अक्षरों में लिखें।", reviewConfirm: "इस रिपोर्ट को स्वीकृत करके समस्या बंद करें?", rejectConfirm: "इस रिपोर्ट को सुधार के लिए पर्यवेक्षक को लौटाएँ?", confirm: "पुष्टि करें", submitted: "जमा करने का समय", reviewed: "समीक्षा का समय", reportPhoto: "पर्यवेक्षक की फोटो", approved: "स्वीकृत", rejected: "अस्वीकृत", open: "खुली समस्याएँ",
  },
};
export type IssueCopy = typeof issueStrings.en;
