"use client";

import React, { useEffect, useMemo, useState } from "react";
import { GeoApi, NalaApi } from "@lib/apiClient";
import ModalPortal from "@components/ui/ModalPortal";

/*
 * KML / KMZ ward import for Nalas (Sweeping: ward beat import).
 *
 * One Folder (or LineString) in the file = one Nala,
 * its Placemarks = NalaPoints. A Nala drawn only as a line
 * gets 5 evenly spaced points generated by the backend.
 */

type Props = {
  onClose: () => void;
  onSuccess: () => void | Promise<void>;
};

const EMPLOYEE_STATUS_LABEL: Record<string, { label: string; color: string; bg: string }> = {
  REGISTERED: { label: "Registered", color: "#047857", bg: "#ecfdf5" },
  NOT_REGISTERED: { label: "Not registered", color: "#b91c1c", bg: "#fef2f2" },
  NOT_SPECIFIED: { label: "Not specified", color: "#64748b", bg: "#f1f5f9" },
  NOT_IN_NALA: { label: "Not in Nala module", color: "#b45309", bg: "#fffbeb" },
  DUPLICATE: { label: "Duplicate name", color: "#b45309", bg: "#fffbeb" }
};

export default function NalaImportModal({ onClose, onSuccess }: Props) {
  const [zones, setZones] = useState<any[]>([]);
  const [wards, setWards] = useState<any[]>([]);
  const [areas, setAreas] = useState<any[]>([]);

  const [zoneId, setZoneId] = useState("");
  const [wardId, setWardId] = useState("");
  const [areaId, setAreaId] = useState("");
  const [file, setFile] = useState<File | null>(null);

  const [preview, setPreview] = useState<any | null>(null);
  const [nalaNames, setNalaNames] = useState<Record<number, string>>({});
  const [selected, setSelected] = useState<Record<number, boolean>>({});

  const [busy, setBusy] = useState<"" | "preview" | "commit">("");
  const [error, setError] = useState("");
  const [result, setResult] = useState("");

  useEffect(() => {
    Promise.allSettled([GeoApi.list("ZONE"), GeoApi.list("WARD"), GeoApi.list("AREA")]).then(
      ([zoneRes, wardRes, areaRes]) => {
        if (zoneRes.status === "fulfilled") setZones(zoneRes.value.nodes || []);
        if (wardRes.status === "fulfilled") setWards(wardRes.value.nodes || []);
        if (areaRes.status === "fulfilled") setAreas(areaRes.value.nodes || []);
      }
    );
  }, []);

  const parentOf = (node: any) => node?.parentId || node?.parent?.id || "";
  const visibleWards = useMemo(() => wards.filter((ward) => !zoneId || parentOf(ward) === zoneId), [wards, zoneId]);
  const visibleAreas = useMemo(() => areas.filter((area) => !wardId || parentOf(area) === wardId), [areas, wardId]);

  const resetPreview = () => {
    setPreview(null);
    setNalaNames({});
    setSelected({});
    setResult("");
  };

  const runPreview = async () => {
    if (!file) {
      setError("Choose a KML or KMZ file.");
      return;
    }

    if (!zoneId || !wardId || !areaId) {
      setError("Select Zone, Ward and Area for the imported Nalas.");
      return;
    }

    try {
      setBusy("preview");
      setError("");
      resetPreview();

      const response = await NalaApi.importPreview(file, { zoneId, wardId, areaId });
      const data = response.preview;

      setPreview(data);
      setNalaNames(
        Object.fromEntries((data?.nalas || []).map((nala: any) => [nala.sourceIndex, nala.suggestedNalaName || ""]))
      );
      // Nalas that already exist in this ward are skipped by default.
      setSelected(
        Object.fromEntries((data?.nalas || []).map((nala: any) => [nala.sourceIndex, !nala.existingSubmission]))
      );
    } catch (err: any) {
      setError(err?.message || "Unable to read this file.");
    } finally {
      setBusy("");
    }
  };

  const chosenNalas = (preview?.nalas || []).filter((nala: any) => selected[nala.sourceIndex]);

  const commit = async () => {
    if (!chosenNalas.length) {
      setError("Select at least one Nala to import.");
      return;
    }

    const blankName = chosenNalas.find((nala: any) => !String(nalaNames[nala.sourceIndex] || "").trim());
    if (blankName) {
      setError("Every imported Nala needs a name.");
      return;
    }

    try {
      setBusy("commit");
      setError("");

      const response = await NalaApi.importCommit({
        zoneId,
        wardId,
        areaId,
        nalas: chosenNalas.map((nala: any) => ({
          sourceIndex: nala.sourceIndex,
          nalaName: String(nalaNames[nala.sourceIndex]).trim(),
          geometry: nala.geometry || null,
          // Generated points are recreated by the backend from the geometry.
          points: nala.pointsGenerated
            ? []
            : (nala.points || []).map((point: any) => ({
              lat: Number(point.lat),
              lng: Number(point.lng),
              name: point.suggestedPointName || undefined,
              // Only employees already in the Nala module can be auto-assigned.
              employeeId: point.employeeStatus === "REGISTERED" ? point.employee?.id || null : null
            }))
        }))
      });

      setResult(response.message || `${response.nalaCount} Nalas imported.`);
      await onSuccess();
    } catch (err: any) {
      setError(err?.message || "Import failed.");
    } finally {
      setBusy("");
    }
  };

  const summary = preview?.employeeSummary;

  return (
    <ModalPortal>
      <div style={overlayStyle}>
        <div style={modalStyle}>
          <div style={headerStyle}>
            <div>
              <div style={{ fontSize: 11, fontWeight: 900, color: "#2563eb", letterSpacing: "0.06em" }}>
                KML / KMZ IMPORT
              </div>
              <div style={{ fontSize: 18, fontWeight: 900, color: "#0f172a", marginTop: 4 }}>Import Nalas</div>
              <div style={{ fontSize: 12, color: "#64748b", marginTop: 2 }}>
                Each folder or line in the file becomes one Nala; its placemarks become NalaPoints (max 50).
              </div>
            </div>
            <button type="button" onClick={onClose} style={closeButtonStyle}>
              ×
            </button>
          </div>

          <div style={{ padding: 20, overflowY: "auto", flex: 1 }}>
            <div style={gridStyle}>
              <select
                value={zoneId}
                onChange={(event) => {
                  setZoneId(event.target.value);
                  setWardId("");
                  setAreaId("");
                  resetPreview();
                }}
                style={inputStyle}
              >
                <option value="">Select Zone</option>
                {zones.map((zone) => (
                  <option key={zone.id} value={zone.id}>
                    {zone.name}
                  </option>
                ))}
              </select>

              <select
                value={wardId}
                onChange={(event) => {
                  setWardId(event.target.value);
                  setAreaId("");
                  resetPreview();
                }}
                style={inputStyle}
                disabled={!zoneId}
              >
                <option value="">Select Ward</option>
                {visibleWards.map((ward) => (
                  <option key={ward.id} value={ward.id}>
                    {ward.name}
                  </option>
                ))}
              </select>

              <select
                value={areaId}
                onChange={(event) => {
                  setAreaId(event.target.value);
                  resetPreview();
                }}
                style={inputStyle}
                disabled={!wardId}
              >
                <option value="">Select Area</option>
                {visibleAreas.map((area) => (
                  <option key={area.id} value={area.id}>
                    {area.name}
                  </option>
                ))}
              </select>

              <input
                type="file"
                accept=".kml,.kmz"
                onChange={(event) => {
                  setFile(event.target.files?.[0] || null);
                  resetPreview();
                }}
                style={{ ...inputStyle, padding: "7px 10px" }}
              />
            </div>

            <div style={{ display: "flex", justifyContent: "flex-end", marginTop: 12 }}>
              <button type="button" onClick={runPreview} disabled={!!busy} style={secondaryButtonStyle}>
                {busy === "preview" ? "Reading file..." : "Preview File"}
              </button>
            </div>

            {error && <div style={errorStyle}>{error}</div>}
            {result && <div style={successStyle}>{result}</div>}

            {preview && (
              <div style={{ marginTop: 16 }}>
                <div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginBottom: 12 }}>
                  <Pill label="Nalas" value={preview.nalaCount} />
                  <Pill label="Points" value={preview.pointCount} />
                  <Pill label="Already registered" value={preview.submissionSummary?.submitted || 0} />
                  {summary && <Pill label="Employees matched" value={summary.registered} />}
                  {summary && summary.notRegistered + summary.notInNala + summary.duplicate > 0 && (
                    <Pill
                      label="Employees not matched"
                      value={summary.notRegistered + summary.notInNala + summary.duplicate}
                      warn
                    />
                  )}
                </div>

                <div style={{ display: "grid", gap: 10 }}>
                  {(preview.nalas || []).map((nala: any) => {
                    const exists = !!nala.existingSubmission;

                    return (
                      <div
                        key={nala.sourceIndex}
                        style={{
                          border: "1px solid #e2e8f0",
                          borderRadius: 12,
                          padding: 12,
                          background: exists ? "#f8fafc" : "#ffffff"
                        }}
                      >
                        <div style={{ display: "flex", gap: 10, alignItems: "center", flexWrap: "wrap" }}>
                          <input
                            type="checkbox"
                            checked={!!selected[nala.sourceIndex]}
                            disabled={exists}
                            onChange={(event) =>
                              setSelected((current) => ({ ...current, [nala.sourceIndex]: event.target.checked }))
                            }
                          />
                          <input
                            value={nalaNames[nala.sourceIndex] || ""}
                            disabled={exists}
                            onChange={(event) =>
                              setNalaNames((current) => ({ ...current, [nala.sourceIndex]: event.target.value }))
                            }
                            style={{ ...inputStyle, flex: 1, minWidth: 180 }}
                          />
                          <span style={{ fontSize: 11, fontWeight: 800, color: "#475569" }}>
                            {nala.pointCount} points{nala.pointsGenerated ? " (generated from line)" : ""}
                          </span>
                          {exists && (
                            <span style={tagStyle("#b45309", "#fffbeb")}>
                              Already registered ({nala.existingSubmission.nalaCode || nala.existingSubmission.status})
                            </span>
                          )}
                          {nala.truncated && <span style={tagStyle("#b91c1c", "#fef2f2")}>Only first 50 points kept</span>}
                        </div>

                        {!nala.pointsGenerated && (nala.points || []).length > 0 && (
                          <div style={{ display: "flex", gap: 6, flexWrap: "wrap", marginTop: 10 }}>
                            {nala.points.map((point: any) => {
                              const status =
                                EMPLOYEE_STATUS_LABEL[point.employeeStatus] || EMPLOYEE_STATUS_LABEL.NOT_SPECIFIED;

                              return (
                                <span
                                  key={point.sourceIndex}
                                  title={point.employeeMessage || point.employee?.name || ""}
                                  style={{
                                    fontSize: 10.5,
                                    fontWeight: 700,
                                    padding: "4px 8px",
                                    borderRadius: 8,
                                    border: "1px solid #e2e8f0",
                                    color: "#334155",
                                    background: "#ffffff"
                                  }}
                                >
                                  {point.suggestedPointName}
                                  {point.employeeName && (
                                    <span style={{ marginLeft: 6, color: status.color }}>
                                      · {point.employee?.name || point.employeeName} ({status.label})
                                    </span>
                                  )}
                                </span>
                              );
                            })}
                          </div>
                        )}
                      </div>
                    );
                  })}
                </div>
              </div>
            )}
          </div>

          <div style={footerStyle}>
            <button type="button" onClick={onClose} style={secondaryButtonStyle}>
              {result ? "Close" : "Cancel"}
            </button>
            {preview && !result && (
              <button type="button" onClick={commit} disabled={!!busy || !chosenNalas.length} style={primaryButtonStyle}>
                {busy === "commit" ? "Importing..." : `Import ${chosenNalas.length} Nala${chosenNalas.length === 1 ? "" : "s"}`}
              </button>
            )}
          </div>
        </div>
      </div>
    </ModalPortal>
  );
}

function Pill({ label, value, warn }: { label: string; value: number; warn?: boolean }) {
  return (
    <span
      style={{
        fontSize: 11,
        fontWeight: 800,
        padding: "5px 10px",
        borderRadius: 999,
        background: warn ? "#fffbeb" : "#eff6ff",
        color: warn ? "#b45309" : "#1d4ed8",
        border: `1px solid ${warn ? "#fde68a" : "#bfdbfe"}`
      }}
    >
      {label}: {value}
    </span>
  );
}

const tagStyle = (color: string, background: string): React.CSSProperties => ({
  fontSize: 10.5,
  fontWeight: 800,
  padding: "3px 8px",
  borderRadius: 8,
  color,
  background
});

const overlayStyle: React.CSSProperties = {
  position: "fixed",
  inset: 0,
  zIndex: 6000,
  background: "rgba(15,23,42,0.58)",
  display: "grid",
  placeItems: "center",
  padding: 20
};

const modalStyle: React.CSSProperties = {
  width: "min(880px, 100%)",
  maxHeight: "92vh",
  background: "#ffffff",
  borderRadius: 18,
  overflow: "hidden",
  display: "flex",
  flexDirection: "column",
  boxShadow: "0 28px 70px rgba(15,23,42,0.3)"
};

const headerStyle: React.CSSProperties = {
  padding: "18px 20px",
  borderBottom: "1px solid #e2e8f0",
  display: "flex",
  justifyContent: "space-between",
  gap: 16
};

const closeButtonStyle: React.CSSProperties = {
  width: 36,
  height: 36,
  borderRadius: 10,
  border: "1px solid #e2e8f0",
  background: "#ffffff",
  fontSize: 20,
  cursor: "pointer"
};

const gridStyle: React.CSSProperties = {
  display: "grid",
  gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
  gap: 10
};

const inputStyle: React.CSSProperties = {
  padding: "9px 12px",
  borderRadius: 10,
  border: "1px solid #cbd5e1",
  fontSize: 12,
  fontWeight: 600,
  color: "#0f172a",
  background: "#ffffff",
  outline: "none"
};

const primaryButtonStyle: React.CSSProperties = {
  padding: "9px 16px",
  borderRadius: 10,
  border: "none",
  background: "#2563eb",
  color: "#ffffff",
  fontSize: 12,
  fontWeight: 800,
  cursor: "pointer"
};

const secondaryButtonStyle: React.CSSProperties = {
  padding: "9px 16px",
  borderRadius: 10,
  border: "1px solid #cbd5e1",
  background: "#ffffff",
  color: "#334155",
  fontSize: 12,
  fontWeight: 800,
  cursor: "pointer"
};

const footerStyle: React.CSSProperties = {
  padding: "14px 20px",
  borderTop: "1px solid #e2e8f0",
  display: "flex",
  justifyContent: "flex-end",
  gap: 10
};

const errorStyle: React.CSSProperties = {
  marginTop: 12,
  padding: "10px 12px",
  borderRadius: 10,
  background: "#fef2f2",
  color: "#b91c1c",
  fontSize: 12,
  fontWeight: 700
};

const successStyle: React.CSSProperties = {
  marginTop: 12,
  padding: "10px 12px",
  borderRadius: 10,
  background: "#ecfdf5",
  color: "#047857",
  fontSize: 12,
  fontWeight: 700
};
